# Generated by Django 5.0.4 on 2024-05-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=1),
            preserve_default=False,
        ),
    ]
