# Generated by Django 5.0.4 on 2024-05-14 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelscomment',
            name='hotels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_comments', to='booking_app.hotels'),
        ),
        migrations.AddIndex(
            model_name='hotels',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['guest_rating'], name='guest_rating_idx'),
        ),
    ]
