# Generated by Django 5.0.4 on 2024-05-09 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_person_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='phone',
        ),
        migrations.AddField(
            model_name='hotels',
            name='persons',
            field=models.ManyToManyField(to='booking_app.person'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='stars',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_time', models.DateTimeField(auto_now_add=True)),
                ('detail', models.CharField(max_length=200, null=True)),
                ('hotels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking_app.hotels')),
                ('persons', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking_app.person')),
            ],
        ),
        migrations.CreateModel(
            name='HotelsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('time_comment', models.DateTimeField(auto_now_add=True)),
                ('hotels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking_app.hotels')),
                ('persons', models.ManyToManyField(to='booking_app.person')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('id_card_number', models.IntegerField(null=True)),
                ('serial', models.CharField(max_length=30, null=True)),
                ('persons', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.person')),
            ],
        ),
    ]
