# Generated by Django 5.0.4 on 2024-05-09 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_remove_hotels_city_remove_hotels_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('experience', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('experience', models.IntegerField(null=True)),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1)),
                ('hobbies', models.ManyToManyField(to='booking_app.hobbies')),
                ('hotels', models.ManyToManyField(to='booking_app.hotels')),
                ('profiles', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.profile')),
            ],
        ),
    ]
