# Generated by Django 5.0.4 on 2024-05-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0006_hobbies_hotelowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbies',
            name='persons',
            field=models.ManyToManyField(to='booking_app.person'),
        ),
    ]
