# Generated by Django 5.0.4 on 2024-06-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0006_alter_user_age_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
