# Generated by Django 5.0.4 on 2024-05-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0007_hobbies_persons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hobbies',
            new_name='Hobbie',
        ),
    ]
