# Generated by Django 5.0.4 on 2024-05-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0008_rename_hobbies_hobbie'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbie',
            name='hotel_owners',
            field=models.ManyToManyField(to='booking_app.hotelowner'),
        ),
    ]
