# Generated by Django 5.0.4 on 2024-05-09 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0010_remove_hobbie_hotel_owners_remove_hobbie_persons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelowner',
            name='profiles',
        ),
        migrations.AddField(
            model_name='profile',
            name='hotel_owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.hotelowner'),
        ),
    ]
